<h1>All users</h1>


<?php if ($searchQuery) : ?>
    <p>Ищем: <?= htmlspecialchars($searchQuery) ?></p>
<?php endif; ?>

<hr>

<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<p>
    <?php foreach ($users as $user) : ?>
        <p>
            <a href="<?= $linkUsers ?>/id/<?= $user['id'] ?>">
                ID: <?= htmlspecialchars($user['id']) ?> | Nickname: <?= htmlspecialchars($user['nickname']) ?> | Email: <?= htmlspecialchars($user['email']) ?>
            </a>
        </p>
    <?php endforeach; ?>
</p>

<hr>

<form action="" method="get">
    <input type="search" name="search_query" value="<?= htmlspecialchars($searchQuery) ?>" />
    <input type="submit" value="Search" />
</form>

<br>

<a href="<?= $linkUsers ?>">Все юзеры</a>
<a href="<?= $linkUsersNew ?>">Добавить нового</a>